name: Testes
version: 1.0
description: Testes Plugin
main: pt.flawless.Testes.Testes
commands:
  giveItem:
    description: Give item command
    aliases: [gi]
  fly:
    description: Fly command
    aliases: [voar]
  comandos:
    description: Commands command
    aliases: [cmds]